name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: ib-gateway-docker

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from tag
        run: echo "{name}=::$(echo ${GITHUB_REF#refs/tags/})::" >> $GITHUB_STATE

      - name: Set up semantic versioning
        uses: paulhatch/semantic-version@v5.0.3
        with:
          bump: patch
          version: ${{ env.VERSION }}
        id: semver

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag "docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.version }}"

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker image
        continue-on-error: true
        id: push-image
        run: |
          docker push "docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.version }}"

          echo "{name}=${{ steps.semver.outputs.version }}" >> $GITHUB_OUTPUT

        
