name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: ib-gateway-docker

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker image
        id: push-image
        run: |
          IMAGE_TAG=$(echo "${{ github.ref }}" | sed 's#.*/##; s/^v//; s/master/latest/')

          docker tag ${{ env.IMAGE_NAME }} "docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG"
          docker push "docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG"

          echo "::set-output name=image-url::docker.pkg.github.com/${{ github.repository }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG"
          echo "::set-output name=image-tag::$IMAGE_TAG"

